### ISSUE TITLE
LG TV unblock for time/date

### ISSUE THREAD

**Issue by Altycoder** [pothirak/adlist#2]
Please unblock the following domain which LG smart TVs (in the UK at least) use to set the correct time and date:

gb.lgtvsdp.com

I really wish LG used NTP but they use the above domain (and probably others similar) by changing the first 2 letters in different locations.  

As soon as I added 1Hosts (Pro) to my NextDNS deny lists my LG TV lost the time on next restart and I had to reset manually after each off/on for several days.  A lot of posts out there claim that LG TVs get the time over the air from DVB antenna but from my testing that's not the case and as soon as the above domain was whitelisted my TV got the correct time/date in less than a second.

**Comment by pothirak** [comment]
I recommend using
https://badmojr.github.io/1Hosts/Lite/domains.txt with https://raw.githubusercontent.com/pothirak/adlist/master/adslist.txt

And add a white list https://raw.githubusercontent.com/pothirak/adlist/master/whitelist.txt

**Comment by Altycoder** [comment]
That's an interesting whitelist. Why whitelist these domains?:

ssl.google-analytics.com
www.google-analytics.com
www.googleadservices.com

**Comment by pothirak** [comment]
The domains that I allow are domains that affect the use of the application.
--------------------------
ssl.google-analytics.com
www.google-analytics.com
It is a domain that affects the use of banking applications to use reward points and privileges. For banking apps in Thailand
--------------------------
www.googleadservices.com
This domain affects page submission to other websites that use Google advertising.
